Joram scrapper code base
carlosrsabreu/devo-abastecer pull request #8
Opened 2022-08-07 21:54 UTC by 13dev

### What this PR does

1. Adds a simple base to search gas prices in the joram website. This is possible by doing a conversion (pdf -> text) and match regex (lowest steps possible) line by line.

Note the first TODO there are some ideas to finish the implementation

### Where should the reviewer start

1. This only adds a first step to close #5 

### Related issues

Related #5

2022-08-08 18:34 UTC, joaoofreitas reviewed
Nice work @13dev! Simple yet so functional.

I would just add a regex for relating the prices to the product that has been sold. 
Maybe store and return a dictionary?

Then we would have a complete _joram_ parser module that we just need to import.

What do you guys think?
@13dev @carlosrsabreu @Dntfreitas

2022-08-08 23:26 UTC, Dntfreitas commented
Yes, it also simplify the integration with the current API

2022-08-09 10:47 UTC, 13dev commented
Thanks 4 the feedback.

I've done some modifications:

- Every price is yield
- Change dir of scrapper to root (so we can use constants.py)
- Add a function to associate prices with gas names

Running the script you will get something like this:

`{'Gasolina IO95': '1,889', 'Gasóleo Rodoviário': '1,789', 'Gasóleo Colorido e Marcado': '1,425'}`

2022-08-09 11:10 UTC, 13dev commented
Update: Perfomance improvement

The script will stop searching for a price when we already have the 3 prices

2022-08-09 17:49 UTC, joaoofreitas requested changes
In general looks good to me. 

I'm sorry to bother about this, but how can we guarantee that the labels correspond to the price?

I suggest adding some verification in `regex` when adding the labels.
Then we can guarantee that the price parsed can indeed correspond to the label.

_We never know when JORAM can change the document format._

2022-08-09 17:51 UTC, joaoofreitas commented
If you need any help or want do discuss it further, just contact me. :)

Thanks to your help! @13dev
Legend.

2022-08-09 18:42 UTC, 13dev commented
Good point!

Changed the regex to match with the label, much cleaner code!

2022-08-09 19:15 UTC, joaoofreitas commented
What a _demon_ of _regex_ right there! 

Needed to test it myself. Works flawlessly.

From my side, it's an approval. Someone need to integrate his changes into the codebase afterwards as a module. 
_(@carlosrsabreu please create an issue if you want to assign it to me)_

Great work, shall be merged soon enough. @13dev 
Now we wait until Thursday, so @carlosrsabreu can approve the changes.

Any thoughts? @carlosrsabreu @Dntfreitas @13dev

2022-08-09 19:52 UTC, 13dev commented on constants.py
> +PDF_GAS_PRICE_REGEX = r'(%s|%s|%s)(?:[\.€\w ]+)(\d{1},\d{3})' % (
i agree, surely have better way to do!

2º group can be `(?:.+)` but it adds 100 more steps

2022-08-11 19:30 UTC, carlosrsabreu commented
@13dev,

Thank you for this PR; it's working perfectly! It's **so great** to have local developers interested in developing open-source community projects 😁

Thank you, @joaoofreitas and @Dntfreitas, for your thoughts and comments!

I will create an issue to integrate this scrapper into the codebase with the mentioned TODOs.

2022-08-11 19:30 UTC, carlosrsabreu approved these changes

2022-08-11 19:31 UTC, merged